/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines.index'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions.$id'
import { Route as PipelinesNewRouteImport } from './routes/pipelines.new'
import { Route as PipelinesIdRouteImport } from './routes/pipelines.$id'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelinesRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const PipelinesNewRoute = PipelinesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PipelinesRoute,
} as any)
const PipelinesIdRoute = PipelinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PipelinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/new': typeof PipelinesNewRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/pipelines/': typeof PipelinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/new': typeof PipelinesNewRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/pipelines': typeof PipelinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/runs': typeof RunsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/new': typeof PipelinesNewRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/pipelines/': typeof PipelinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pipelines'
    | '/runs'
    | '/settings'
    | '/subscriptions'
    | '/pipelines/$id'
    | '/pipelines/new'
    | '/subscriptions/$id'
    | '/pipelines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runs'
    | '/settings'
    | '/subscriptions'
    | '/pipelines/$id'
    | '/pipelines/new'
    | '/subscriptions/$id'
    | '/pipelines'
  id:
    | '__root__'
    | '/'
    | '/pipelines'
    | '/runs'
    | '/settings'
    | '/subscriptions'
    | '/pipelines/$id'
    | '/pipelines/new'
    | '/subscriptions/$id'
    | '/pipelines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelinesRoute: typeof PipelinesRouteWithChildren
  RunsRoute: typeof RunsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/pipelines/new': {
      id: '/pipelines/new'
      path: '/new'
      fullPath: '/pipelines/new'
      preLoaderRoute: typeof PipelinesNewRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/pipelines/$id': {
      id: '/pipelines/$id'
      path: '/$id'
      fullPath: '/pipelines/$id'
      preLoaderRoute: typeof PipelinesIdRouteImport
      parentRoute: typeof PipelinesRoute
    }
  }
}

interface PipelinesRouteChildren {
  PipelinesIdRoute: typeof PipelinesIdRoute
  PipelinesNewRoute: typeof PipelinesNewRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
}

const PipelinesRouteChildren: PipelinesRouteChildren = {
  PipelinesIdRoute: PipelinesIdRoute,
  PipelinesNewRoute: PipelinesNewRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
}

const PipelinesRouteWithChildren = PipelinesRoute._addFileChildren(
  PipelinesRouteChildren,
)

interface SubscriptionsRouteChildren {
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsIdRoute: SubscriptionsIdRoute,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelinesRoute: PipelinesRouteWithChildren,
  RunsRoute: RunsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
